import Link from 'next/link';
import { getLandingCopy } from '@/lib/i18n';
import { changeLandingLocale } from './locale';
import { LandingSearch } from './search';
import './landing.css';

export async function Landing() {
 const { locale, copy:c } = await getLandingCopy();
 const nav = ['calatori','firme','rute','pilot'];
 const localeForm = <form action={changeLandingLocale} className="landing-languages"><button name="locale" value="ro" aria-pressed={locale==='ro'}>RO</button><button name="locale" value="de" aria-pressed={locale==='de'}>DE</button></form>;
 return <div className="landing">
  <header className="landing-header"><div className="landing-container header-inner"><Link className="landing-brand" href="/" aria-label="TransportOS"><span className="brand-icon" aria-hidden="true"/>TransportOS</Link><nav className="desktop-nav" aria-label={c.menu}>{nav.map((id,i)=><a key={id} href={'#'+id}>{c.nav[i]}</a>)}</nav><div className="header-actions">{localeForm}<Link className="landing-button outline login-link" href="/login?next=/">{c.login}</Link><details className="mobile-menu"><summary aria-label={c.menu}>☰</summary><nav>{nav.map((id,i)=><a key={id} href={'#'+id}>{c.nav[i]}</a>)}<Link href="/login?next=/">{c.login}</Link></nav></details></div></div></header>
  <main>
   <section className="landing-hero"><div className="landing-container hero-grid"><div className="hero-copy"><h1>{locale === 'ro' ? [[0,2],[2,6],[6,9],[9,10]].map(([start,end])=>c.title.split(' ').slice(start,end).join(' ')).map((line,i)=><span key={i}>{line}{i < 3 ? ' ' : ''}</span>) : c.title}</h1><p className="desktop-only hero-intro">{c.intro}</p><p className="mobile-only hero-intro">{c.introMobile}</p><div className="hero-actions desktop-only"><a className="landing-button yellow" href="#cauta-cursa">{c.search}</a><a className="landing-button outline" href="#firme">{c.company}</a></div></div>
   <figure className="departures"><div className="departure-sign"><header><strong className="desktop-only">{c.boardTitle}</strong><strong className="mobile-only">{c.boardMobile}</strong><span className="desktop-only sign-location">{c.location}</span></header>{['Wien','München','Stuttgart'].map((city,i)=><div className="departure" key={city}><span className={'direction direction-'+i} aria-hidden="true"/><div><h2>{city}</h2><p className="desktop-only">{c.boardDetails[i]}</p><p className="mobile-only">{c.boardMobileDetails[i]}</p></div><b className="eta">{[14,31,47][i]} min</b></div>)}</div><figcaption>{c.example}</figcaption></figure>
   <LandingSearch copy={c}/><a className="landing-button outline mobile-only mobile-company" href="#firme">{c.company}</a></div></section>
   <section id="calatori" className="landing-problem white"><div className="landing-container"><h2>{c.problem}</h2><div className="problem-columns">{[[c.traveler,c.travelerProblems],[c.firm,c.firmProblems]].map(([title,rows],i)=><div key={i}><h3>{title as string}</h3><ul>{(rows as readonly string[]).map(text=><li key={text}>{text}</li>)}</ul></div>)}</div></div></section>
   <section id="cum-functioneaza" className="landing-how"><div className="landing-container"><h2>{c.how}</h2><ol className="steps">{c.steps.map(([title,text],i)=><li key={title}><b className="step-number">{i+1}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><h2 className="services-heading">{c.servicesTitle}</h2><div className="services">{c.services.map(([title,text],i)=><div className="service" key={title}><span className={'service-icon service-icon-'+i} aria-hidden="true"/><h3>{title}</h3><p className="desktop-only">{text}</p><p className="mobile-only">{c.servicesMobile[i]}</p></div>)}</div></div></section>
   <section id="firme" className="landing-firms white"><div className="landing-container"><h2>{c.firmsTitle}</h2><p className="firms-intro">{c.firmsIntro}</p><div className="seat-demo"><div className="desktop-only"><div className="seat-cities"><span/><b>Timișoara</b><b>Budapest</b><b>Wien</b><b>Linz</b><b>Salzburg</b><b>München</b></div><div className="seat-segments"><b>{c.seat}</b><strong className="segment ana">{c.ana}</strong><strong className="segment available">{c.free}</strong><strong className="segment markus">{c.markus}</strong></div><p>{c.seatNote}</p></div><div className="mobile-only"><b>{c.seatMobile}</b><div className="mobile-segment"><b>Timișoara<br/>Wien</b><strong className="segment ana">Ana</strong></div><div className="mobile-segment"><b>Wien Linz</b><strong className="segment available">{c.free}</strong></div><div className="mobile-segment"><b>Linz München</b><strong className="segment markus">Markus</strong></div><p>{c.seatNoteMobile}</p></div></div><div className="firm-features">{c.features.map(([title,text],i)=><article key={title}><h3>{title}</h3><p className="desktop-only">{text}</p><p className="mobile-only">{c.featuresMobile[i]}</p></article>)}</div></div></section>
   <section id="rute" className="landing-routes"><div className="landing-container routes-grid"><div><h2>{c.routesTitle}</h2><p className="desktop-only">{c.routesIntro}</p><p className="mobile-only">{c.routesIntroMobile}</p></div><div className="route-signs">{c.routes.map((route,i)=><div key={route}><strong>{route}</strong><b>{['RO AT','RO DE','AT DE'][i]}</b></div>)}</div></div></section>
   <section id="pilot" className="landing-pilot"><div className="landing-container pilot-grid"><div className="pilot-copy"><h2>{c.pilotTitle}</h2><p className="desktop-only">{c.pilotIntro}</p><p className="mobile-only">{c.pilotIntroMobile}</p></div><dl className="pilot-card"><div><dt>{c.subscription}</dt><dd>{c.price}</dd></div><div><dt>{c.commission}</dt><dd>0%</dd></div><div><dt>{c.pilotConditions}</dt><dd>[CONDIȚII PILOT]</dd></div><div><dt>{c.pilotPlaces}</dt><dd>{c.firmsCount}</dd></div></dl><div className="pilot-actions"><Link className="landing-button yellow" href="/inregistrare-firma">{c.apply}</Link><span className="landing-button outline" aria-disabled="true">{c.email}</span></div></div></section>
  </main>
  <footer className="landing-footer"><div className="landing-container"><div className="footer-columns"><div className="footer-brand"><strong>TransportOS</strong><p>{c.footerIntro}</p></div><div><h3>{c.travelers}</h3><a href="#cauta-cursa">{c.search}</a><a href="#cum-functioneaza">{c.howLink}</a><a href="#rute">{c.nav[2]}</a></div><div><h3>{c.companies}</h3><a href="#firme">{c.featuresLink}</a><a href="#pilot">{c.nav[3]}</a><Link href="/login?next=/">{c.login}</Link></div><div><h3>{c.legal}</h3><span>{c.terms}</span><span>{c.privacy}</span><span>{c.cookies}</span></div></div><p className="copyright">© 2026 TransportOS. EvaMaria Shop S.R.L. · CUI 44420154 · J35/2346/2020 · Str. Principală 793, 307241 Bulgăruș, jud. Timiș, România</p></div></footer>
 </div>;
}
